name: Basic CI/CD
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Deploy to Render
        uses: JorgeLNJunior/render-deploy@v1.4.5
        with:
          # Render service id
          service_id: ${{ secrets.RENDER_SERVICE_ID }}
          # Render api key
          api_key: ${{ secrets.RENDER_API_KEY }}
